
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/haunted-harvest/issues" #optional


[[mods]] #mandatory
    modId="hauntedharvest" #mandatory
    version = "${version}"
    displayName="Haunted Harvest" #mandatory
    logoFile="icon.png" #optional
    credits="MehVahdJukaar, Plantkillable" #optional
    authors="MehVahdJukaar, Plantkillable" #optional

    description='''
    Villagers Trick or Treating, Pumpkin Carving and Corn
    '''
    modUrl="https://www.curseforge.com/minecraft/mc-mods/haunted-harvest" #optional

[modproperties.hauntedharvest]
    catalogueItemIcon = "hauntedharvest:grim_apple" #catalogue icon
    configuredBackground = "minecraft:textures/block/cracked_stone_bricks.png"

[[dependencies.hauntedharvest]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.hauntedharvest]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hauntedharvest]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.4-2.4.10,]"
    ordering="NONE"
    side="BOTH"
